import { z } from "zod";
import { publicProcedure, router } from "./_core/trpc";
import { getDb } from "./db";
import { sshConfig } from "../drizzle/schema";
import { eq } from "drizzle-orm";
import { exec } from "child_process";
import { promisify } from "util";
import * as fs from "fs/promises";

const execAsync = promisify(exec);

export const sshConfigRouter = router({
  /**
   * 获取SSH配置
   */
  get: publicProcedure.query(async () => {
    const db = await getDb();
    if (!db) throw new Error("数据库连接失败");

    const [config] = await db.select().from(sshConfig).limit(1);

    // 如果没有配置,返回默认值
    if (!config) {
      return {
        port: 22,
        permitRootLogin: "prohibit-password" as const,
        passwordAuthentication: 1,
        pubkeyAuthentication: 1,
        allowUsers: null,
        denyUsers: null,
        maxAuthTries: 6,
        loginGraceTime: 120,
        clientAliveInterval: 300,
        clientAliveCountMax: 3,
        pendingChanges: 0,
        applyStatus: "success" as const,
      };
    }

    return config;
  }),

  /**
   * 更新SSH配置
   */
  update: publicProcedure
    .input(
      z.object({
        port: z.number().min(1).max(65535).optional(),
        permitRootLogin: z.enum(["yes", "no", "prohibit-password"]).optional(),
        passwordAuthentication: z.number().min(0).max(1).optional(),
        pubkeyAuthentication: z.number().min(0).max(1).optional(),
        allowUsers: z.string().nullable().optional(),
        denyUsers: z.string().nullable().optional(),
        maxAuthTries: z.number().min(1).max(100).optional(),
        loginGraceTime: z.number().min(0).max(3600).optional(),
        clientAliveInterval: z.number().min(0).max(3600).optional(),
        clientAliveCountMax: z.number().min(0).max(100).optional(),
      })
    )
    .mutation(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new Error("数据库连接失败");

      // 检查是否已有配置
      const [existing] = await db.select().from(sshConfig).limit(1);

      if (existing) {
        // 更新现有配置
        await db
          .update(sshConfig)
          .set({
            ...input,
            pendingChanges: 1,
            applyStatus: "pending",
          })
          .where(eq(sshConfig.id, existing.id));
      } else {
        // 创建新配置
        await db.insert(sshConfig).values({
          ...input,
          pendingChanges: 1,
          applyStatus: "pending",
        });
      }

      return { success: true };
    }),

  /**
   * 应用SSH配置到系统
   */
  applyConfig: publicProcedure.mutation(async () => {
    const db = await getDb();
    if (!db) throw new Error("数据库连接失败");

    try {
      // 获取当前配置
      const [config] = await db.select().from(sshConfig).limit(1);
      if (!config) {
        throw new Error("未找到SSH配置");
      }

      // 生成sshd_config内容
      let sshdConfig = `
# Generated by URouterOS
Port ${config.port}
PermitRootLogin ${config.permitRootLogin}
PasswordAuthentication ${config.passwordAuthentication ? "yes" : "no"}
PubkeyAuthentication ${config.pubkeyAuthentication ? "yes" : "no"}
MaxAuthTries ${config.maxAuthTries}
LoginGraceTime ${config.loginGraceTime}
ClientAliveInterval ${config.clientAliveInterval}
ClientAliveCountMax ${config.clientAliveCountMax}
`;

      if (config.allowUsers) {
        sshdConfig += `AllowUsers ${config.allowUsers}\n`;
      }

      if (config.denyUsers) {
        sshdConfig += `DenyUsers ${config.denyUsers}\n`;
      }

      // 备份原配置
      await execAsync("sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak");

      // 写入新配置
      await fs.writeFile("/tmp/sshd_config_new", sshdConfig);
      await execAsync("sudo mv /tmp/sshd_config_new /etc/ssh/sshd_config");

      // 测试配置
      await execAsync("sudo sshd -t");

      // 重启SSH服务
      await execAsync("sudo systemctl restart sshd");

      // 更新数据库状态
      await db
        .update(sshConfig)
        .set({
          pendingChanges: 0,
          lastAppliedAt: new Date(),
          applyStatus: "success",
          applyError: null,
        })
        .where(eq(sshConfig.id, config.id));

      return { success: true };
    } catch (error: any) {
      // 更新失败状态
      const [config] = await db.select().from(sshConfig).limit(1);
      if (config) {
        await db
          .update(sshConfig)
          .set({
            applyStatus: "failed",
            applyError: error.message,
          })
          .where(eq(sshConfig.id, config.id));
      }

      throw error;
    }
  }),

  /**
   * 复位未应用的修改
   */
  revert: publicProcedure.mutation(async () => {
    const db = await getDb();
    if (!db) throw new Error("数据库连接失败");

    // 简单实现:将pendingChanges设为0
    const [config] = await db.select().from(sshConfig).limit(1);
    if (config) {
      await db
        .update(sshConfig)
        .set({ pendingChanges: 0 })
        .where(eq(sshConfig.id, config.id));
    }

    return { success: true };
  }),
});
