/**
 * DHCP静态租约配置应用器
 * 负责将数据库中的配置应用到系统(dnsmasq)
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import * as fs from 'fs/promises';
import * as path from 'path';

const execAsync = promisify(exec);

const DNSMASQ_CONFIG_DIR = '/etc/dnsmasq.d';
const DNSMASQ_STATIC_LEASES_FILE = path.join(DNSMASQ_CONFIG_DIR, 'static-leases.conf');

export interface DhcpStaticLease {
  id: number;
  macAddress: string;
  ipAddress: string;
  hostname?: string | null;
  enabled: number | null;
}

/**
 * 应用所有DHCP静态租约到系统
 */
export async function applyDhcpStaticLeases(leases: DhcpStaticLease[]): Promise<{ success: boolean; message: string }> {
  try {
    // 确保配置目录存在
    try {
      await fs.mkdir(DNSMASQ_CONFIG_DIR, { recursive: true });
    } catch (error) {
      // 目录可能已存在
    }

    // 生成配置文件内容
    const configLines = [
      '# URouterOS Static DHCP Leases',
      '# Generated by URouterOS - DO NOT EDIT MANUALLY',
      '',
    ];

    // 只添加启用的租约
    const enabledLeases = leases.filter(lease => lease.enabled === 1);
    
    for (const lease of enabledLeases) {
      if (lease.hostname) {
        configLines.push(`dhcp-host=${lease.macAddress},${lease.ipAddress},${lease.hostname}`);
      } else {
        configLines.push(`dhcp-host=${lease.macAddress},${lease.ipAddress}`);
      }
    }

    configLines.push('');

    // 写入配置文件
    await fs.writeFile(DNSMASQ_STATIC_LEASES_FILE, configLines.join('\n'), 'utf-8');

    // 重启dnsmasq服务
    try {
      await execAsync('systemctl restart dnsmasq');
      return { 
        success: true, 
        message: `成功应用${enabledLeases.length}条静态租约配置` 
      };
    } catch (error) {
      return { 
        success: false, 
        message: `配置已保存但重启服务失败: ${error instanceof Error ? error.message : String(error)}` 
      };
    }
  } catch (error) {
    console.error('Failed to apply DHCP static leases:', error);
    return { 
      success: false, 
      message: `应用配置失败: ${error instanceof Error ? error.message : String(error)}` 
    };
  }
}

/**
 * 验证MAC地址格式
 */
export function validateMacAddress(mac: string): boolean {
  const macRegex = /^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$/;
  return macRegex.test(mac);
}

/**
 * 验证IP地址格式
 */
export function validateIpAddress(ip: string): boolean {
  const ipRegex = /^(\d{1,3}\.){3}\d{1,3}$/;
  if (!ipRegex.test(ip)) return false;
  
  const parts = ip.split('.');
  return parts.every(part => {
    const num = parseInt(part, 10);
    return num >= 0 && num <= 255;
  });
}

/**
 * 清空所有静态租约配置
 */
export async function clearDhcpStaticLeases(): Promise<{ success: boolean; message: string }> {
  try {
    // 写入空配置文件
    const configLines = [
      '# URouterOS Static DHCP Leases',
      '# Generated by URouterOS - DO NOT EDIT MANUALLY',
      '',
      '# No static leases configured',
      '',
    ];

    await fs.writeFile(DNSMASQ_STATIC_LEASES_FILE, configLines.join('\n'), 'utf-8');

    // 重启dnsmasq服务
    try {
      await execAsync('systemctl restart dnsmasq');
      return { success: true, message: '已清空所有静态租约配置' };
    } catch (error) {
      return { 
        success: false, 
        message: `配置已清空但重启服务失败: ${error instanceof Error ? error.message : String(error)}` 
      };
    }
  } catch (error) {
    console.error('Failed to clear DHCP static leases:', error);
    return { 
      success: false, 
      message: `清空配置失败: ${error instanceof Error ? error.message : String(error)}` 
    };
  }
}
