/**
 * DHCP/DNS服务管理
 * 使用dnsmasq提供DHCP和DNS服务
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import * as fs from 'fs/promises';
import * as path from 'path';

const execAsync = promisify(exec);

const DNSMASQ_CONFIG_DIR = '/etc/dnsmasq.d';
const DNSMASQ_CONFIG_FILE = path.join(DNSMASQ_CONFIG_DIR, 'urouteros.conf');
const DNSMASQ_LEASES_FILE = '/var/lib/misc/dnsmasq.leases';
const DNSMASQ_STATIC_LEASES_FILE = path.join(DNSMASQ_CONFIG_DIR, 'static-leases.conf');

export interface DHCPConfig {
  interface: string;
  dhcp_start: string;
  dhcp_end: string;
  dhcp_time: string;
  dns_servers: string[];
  domain?: string;
  enabled: boolean;
}

export interface DHCPLease {
  mac: string;
  ip: string;
  hostname: string;
  expires: string;
}

export interface DHCPStatus {
  running: boolean;
  configured: boolean;
  leases_count: number;
}

/**
 * 获取DHCP配置
 */
export async function getDHCPConfig(): Promise<DHCPConfig | null> {
  try {
    const content = await fs.readFile(DNSMASQ_CONFIG_FILE, 'utf-8');
    const config: Partial<DHCPConfig> = {
      interface: 'br-lan',
      dhcp_start: '192.168.188.100',
      dhcp_end: '192.168.188.200',
      dhcp_time: '12h',
      dns_servers: ['8.8.8.8', '8.8.4.4'],
      enabled: true,
    };

    // 解析配置文件
    const lines = content.split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      
      // interface=br-lan
      if (trimmed.startsWith('interface=')) {
        config.interface = trimmed.split('=')[1];
      }
      
      // dhcp-range=192.168.188.100,192.168.188.200,12h
      if (trimmed.startsWith('dhcp-range=')) {
        const parts = trimmed.split('=')[1].split(',');
        if (parts.length >= 3) {
          config.dhcp_start = parts[0];
          config.dhcp_end = parts[1];
          config.dhcp_time = parts[2];
        }
      }
      
      // server=8.8.8.8
      if (trimmed.startsWith('server=')) {
        const dns = trimmed.split('=')[1];
        if (!config.dns_servers) config.dns_servers = [];
        config.dns_servers.push(dns);
      }
      
      // domain=local
      if (trimmed.startsWith('domain=')) {
        config.domain = trimmed.split('=')[1];
      }
    }

    return config as DHCPConfig;
  } catch (error) {
    console.error('Failed to read DHCP config:', error);
    return null;
  }
}

/**
 * 配置DHCP服务
 */
export async function configureDHCP(config: DHCPConfig): Promise<{ success: boolean; message: string }> {
  try {
    // 确保配置目录存在
    try {
      await fs.mkdir(DNSMASQ_CONFIG_DIR, { recursive: true });
    } catch (error) {
      // 目录可能已存在
    }

    // 生成配置文件内容
    const configLines = [
      '# URouterOS DHCP/DNS Configuration',
      '# Generated by URouterOS',
      '',
      `# Listen on interface`,
      `interface=${config.interface}`,
      '',
      `# DHCP range`,
      `dhcp-range=${config.dhcp_start},${config.dhcp_end},${config.dhcp_time}`,
      '',
      `# DNS servers`,
    ];

    for (const dns of config.dns_servers) {
      configLines.push(`server=${dns}`);
    }

    if (config.domain) {
      configLines.push('');
      configLines.push(`# Domain`);
      configLines.push(`domain=${config.domain}`);
    }

    configLines.push('');
    configLines.push('# Additional options');
    configLines.push('dhcp-authoritative');
    configLines.push('dhcp-leasefile=/var/lib/misc/dnsmasq.leases');
    configLines.push('');

    // 写入配置文件
    await fs.writeFile(DNSMASQ_CONFIG_FILE, configLines.join('\n'), 'utf-8');

    // 重启dnsmasq服务
    try {
      await execAsync('sudo systemctl restart dnsmasq');
      return { success: true, message: 'DHCP配置成功并已重启服务' };
    } catch (error) {
      return { success: false, message: `配置已保存但重启服务失败: ${error instanceof Error ? error.message : String(error)}` };
    }
  } catch (error) {
    console.error('Failed to configure DHCP:', error);
    return { success: false, message: `配置失败: ${error instanceof Error ? error.message : String(error)}` };
  }
}

/**
 * 获取DHCP租约列表
 */
export async function getDHCPLeases(): Promise<DHCPLease[]> {
  try {
    const content = await fs.readFile(DNSMASQ_LEASES_FILE, 'utf-8');
    const leases: DHCPLease[] = [];
    
    const lines = content.trim().split('\n');
    for (const line of lines) {
      if (!line.trim()) continue;
      
      // dnsmasq租约格式: timestamp mac ip hostname client-id
      const parts = line.split(/\s+/);
      if (parts.length >= 4) {
        const timestamp = parseInt(parts[0]);
        const expiresDate = new Date(timestamp * 1000);
        
        leases.push({
          mac: parts[1],
          ip: parts[2],
          hostname: parts[3] === '*' ? 'Unknown' : parts[3],
          expires: expiresDate.toISOString(),
        });
      }
    }
    
    return leases;
  } catch (error) {
    console.error('Failed to read DHCP leases:', error);
    return [];
  }
}

/**
 * 获取静态租约列表
 */
export async function getStaticLeases(): Promise<Array<{ mac: string; ip: string; hostname?: string }>> {
  try {
    const content = await fs.readFile(DNSMASQ_STATIC_LEASES_FILE, 'utf-8');
    const leases: Array<{ mac: string; ip: string; hostname?: string }> = [];
    
    const lines = content.split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      
      // dhcp-host=aa:bb:cc:dd:ee:ff,192.168.1.100,hostname
      if (trimmed.startsWith('dhcp-host=')) {
        const parts = trimmed.split('=')[1].split(',');
        if (parts.length >= 2) {
          leases.push({
            mac: parts[0],
            ip: parts[1],
            hostname: parts[2] || undefined,
          });
        }
      }
    }
    
    return leases;
  } catch (error) {
    // 文件可能不存在
    return [];
  }
}

/**
 * 添加静态租约
 */
export async function addStaticLease(lease: { mac: string; ip: string; hostname?: string }): Promise<{ success: boolean; message: string }> {
  try {
    // 读取现有静态租约
    let content = '';
    try {
      content = await fs.readFile(DNSMASQ_STATIC_LEASES_FILE, 'utf-8');
    } catch (error) {
      // 文件不存在,创建新文件
      content = '# URouterOS Static DHCP Leases\n\n';
    }

    // 检查是否已存在
    const lines = content.split('\n');
    for (const line of lines) {
      if (line.includes(lease.mac)) {
        return { success: false, message: 'MAC地址已存在' };
      }
    }

    // 添加新租约
    const newLine = lease.hostname 
      ? `dhcp-host=${lease.mac},${lease.ip},${lease.hostname}`
      : `dhcp-host=${lease.mac},${lease.ip}`;
    
    content += newLine + '\n';
    
    // 写入文件
    await fs.writeFile(DNSMASQ_STATIC_LEASES_FILE, content, 'utf-8');

    // 重启dnsmasq
    try {
      await execAsync('sudo systemctl restart dnsmasq');
      return { success: true, message: '静态租约添加成功' };
    } catch (error) {
      return { success: false, message: `租约已添加但重启服务失败: ${error instanceof Error ? error.message : String(error)}` };
    }
  } catch (error) {
    console.error('Failed to add static lease:', error);
    return { success: false, message: `添加失败: ${error instanceof Error ? error.message : String(error)}` };
  }
}

/**
 * 删除静态租约
 */
export async function deleteStaticLease(mac: string): Promise<{ success: boolean; message: string }> {
  try {
    const content = await fs.readFile(DNSMASQ_STATIC_LEASES_FILE, 'utf-8');
    const lines = content.split('\n');
    const newLines = lines.filter(line => !line.includes(mac));
    
    if (lines.length === newLines.length) {
      return { success: false, message: 'MAC地址不存在' };
    }

    await fs.writeFile(DNSMASQ_STATIC_LEASES_FILE, newLines.join('\n'), 'utf-8');

    // 重启dnsmasq
    try {
      await execAsync('sudo systemctl restart dnsmasq');
      return { success: true, message: '静态租约删除成功' };
    } catch (error) {
      return { success: false, message: `租约已删除但重启服务失败: ${error instanceof Error ? error.message : String(error)}` };
    }
  } catch (error) {
    console.error('Failed to delete static lease:', error);
    return { success: false, message: `删除失败: ${error instanceof Error ? error.message : String(error)}` };
  }
}

/**
 * 获取DHCP/DNS服务状态
 */
export async function getDHCPStatus(): Promise<DHCPStatus> {
  try {
    // 检查dnsmasq服务状态
    try {
      await execAsync('sudo systemctl is-active dnsmasq');
      const running = true;
      
      // 检查是否已配置
      let configured = false;
      try {
        await fs.access(DNSMASQ_CONFIG_FILE);
        configured = true;
      } catch (error) {
        // 配置文件不存在
      }

      // 获取租约数量
      const leases = await getDHCPLeases();
      
      return {
        running,
        configured,
        leases_count: leases.length,
      };
    } catch (error) {
      // 服务未运行
      return {
        running: false,
        configured: false,
        leases_count: 0,
      };
    }
  } catch (error) {
    console.error('Failed to get DHCP status:', error);
    return {
      running: false,
      configured: false,
      leases_count: 0,
    };
  }
}

/**
 * 启动DHCP/DNS服务
 */
export async function startDHCP(): Promise<{ success: boolean; message: string }> {
  try {
    await execAsync('sudo systemctl start dnsmasq');
    return { success: true, message: 'DHCP/DNS服务已启动' };
  } catch (error) {
    console.error('Failed to start DHCP:', error);
    return { success: false, message: `启动失败: ${error instanceof Error ? error.message : String(error)}` };
  }
}

/**
 * 停止DHCP/DNS服务
 */
export async function stopDHCP(): Promise<{ success: boolean; message: string }> {
  try {
    await execAsync('sudo systemctl stop dnsmasq');
    return { success: true, message: 'DHCP/DNS服务已停止' };
  } catch (error) {
    console.error('Failed to stop DHCP:', error);
    return { success: false, message: `停止失败: ${error instanceof Error ? error.message : String(error)}` };
  }
}

/**
 * 重启DHCP/DNS服务
 */
export async function restartDHCP(): Promise<{ success: boolean; message: string }> {
  try {
    await execAsync('sudo systemctl restart dnsmasq');
    return { success: true, message: 'DHCP/DNS服务已重启' };
  } catch (error) {
    console.error('Failed to restart DHCP:', error);
    return { success: false, message: `重启失败: ${error instanceof Error ? error.message : String(error)}` };
  }
}
